Basic calculator working
IvanG16/Desafios pull request #39
Opened 2023-09-28 20:19 UTC by IvanG16

2023-10-03 13:28 UTC, mfigares reviewed
I n order to evaluate this PR properly, you should get the node_modules folder in the gitignore. If not, we have this massive file count that slows down even the github PR interphase, and it shouldn't be necessary to keep them in the repo

2023-10-03 18:45 UTC, naipeloz requested changes

2023-10-03 18:45 UTC, naipeloz commented on src/components/button.jsx
> +  buttonClick: PropTypes.func.isRequired,
The name must be more descriptive. Something like handleClick or onClick

2023-10-03 18:45 UTC, naipeloz commented on src/components/button.jsx
> +  const backgroundColor = valueType === 'operand' ? styles.concat(' bg-stone-50') : styles.concat(' bg-stone-300');
It is ok. But, you could simplify the style definition doing something like this:
```
const styles = `w-[81px] h-[45px] p-2.5 rounded-[5px] border border-black flex-col justify-center items-center gap-2.5 inline-flex ${valueType === 'operand' ? 'bg-stone-50' : 'bg-stone-300'} `
```

2023-10-03 18:45 UTC, naipeloz commented on package-lock.json
It is not mandatory. But, it could be ignored by git

2023-10-03 18:45 UTC, naipeloz commented on README.md
Update the README. with a nice description of your practice

2023-10-17 15:14 UTC, mfigares commented on package-lock.json
I think I'd leave it, that way we have the actual _full_ dependency tree for the project, don't you think? 
Most of the time, it doesn't matter but sometimes, having a package-lock.json lets you identify and fix dependency issues ()

2023-10-18 21:05 UTC, mfigares approved these changes
Almost legally approved! 🚀

2023-10-18 21:05 UTC, merged